import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL ?? "file:./dev.db",
});
const prisma = new PrismaClient({ adapter });

const img = (texto: string) =>
  `https://placehold.co/600x600.png?text=${encodeURIComponent(texto)}`;

const productos = [
  // Ropa - Hombre
  {
    nombre: "Polo básico algodón",
    descripcion: "Polo de algodón 100% pima, corte regular, ideal para el día a día.",
    precio: 39.9,
    categoria: "Ropa",
    subcategoria: "Hombre",
    stock: 40,
    imagenUrl: img("Polo Basico Hombre"),
    marca: "Urbano",
    destacado: true,
  },
  {
    nombre: "Camisa a cuadros manga larga",
    descripcion: "Camisa de franela a cuadros, manga larga, perfecta para climas fríos.",
    precio: 69.9,
    categoria: "Ropa",
    subcategoria: "Hombre",
    stock: 25,
    imagenUrl: img("Camisa a Cuadros"),
    marca: "Northline",
  },
  {
    nombre: "Pantalón jean slim fit",
    descripcion: "Jean de corte slim fit, denim elástico para mayor comodidad.",
    precio: 99.9,
    categoria: "Ropa",
    subcategoria: "Hombre",
    stock: 30,
    imagenUrl: img("Jean Slim Hombre"),
    marca: "Levi's",
    destacado: true,
  },
  {
    nombre: "Casaca cortavientos",
    descripcion: "Casaca impermeable y liviana, ideal para actividades al aire libre.",
    precio: 129.9,
    categoria: "Ropa",
    subcategoria: "Hombre",
    stock: 18,
    imagenUrl: img("Casaca Cortavientos"),
    marca: "Northline",
  },
  {
    nombre: "Short deportivo hombre",
    descripcion: "Short de secado rápido con bolsillos laterales, ideal para entrenar.",
    precio: 44.9,
    categoria: "Ropa",
    subcategoria: "Hombre",
    stock: 35,
    imagenUrl: img("Short Deportivo"),
    marca: "Nike",
  },
  {
    nombre: "Sweater cuello redondo",
    descripcion: "Sweater de algodón con cuello redondo, disponible en varios colores.",
    precio: 79.9,
    categoria: "Ropa",
    subcategoria: "Hombre",
    stock: 22,
    imagenUrl: img("Sweater Hombre"),
    marca: "Urbano",
  },

  // Ropa - Mujer
  {
    nombre: "Blusa manga larga",
    descripcion: "Blusa de vestir manga larga, tela suave y fresca.",
    precio: 59.9,
    categoria: "Ropa",
    subcategoria: "Mujer",
    stock: 28,
    imagenUrl: img("Blusa Mujer"),
    marca: "Zara",
    destacado: true,
  },
  {
    nombre: "Vestido casual verano",
    descripcion: "Vestido ligero de tirantes, estampado floral, ideal para el verano.",
    precio: 89.9,
    categoria: "Ropa",
    subcategoria: "Mujer",
    stock: 20,
    imagenUrl: img("Vestido Casual"),
    marca: "Zara",
    destacado: true,
  },
  {
    nombre: "Jean tiro alto",
    descripcion: "Jean de tiro alto, corte skinny, con elastano para mayor comodidad.",
    precio: 109.9,
    categoria: "Ropa",
    subcategoria: "Mujer",
    stock: 26,
    imagenUrl: img("Jean Tiro Alto"),
    marca: "Levi's",
  },
  {
    nombre: "Chompa oversize",
    descripcion: "Chompa de punto oversize, tejido grueso, muy abrigadora.",
    precio: 94.9,
    categoria: "Ropa",
    subcategoria: "Mujer",
    stock: 15,
    imagenUrl: img("Chompa Oversize"),
    marca: "H&M",
  },
  {
    nombre: "Leggings deportivo mujer",
    descripcion: "Leggings de compresión, tela transpirable, cintura alta.",
    precio: 54.9,
    categoria: "Ropa",
    subcategoria: "Mujer",
    stock: 32,
    imagenUrl: img("Leggings Deportivo"),
    marca: "Adidas",
  },
  {
    nombre: "Chaqueta denim mujer",
    descripcion: "Chaqueta de jean clásica, corte entallado.",
    precio: 119.9,
    categoria: "Ropa",
    subcategoria: "Mujer",
    stock: 17,
    imagenUrl: img("Chaqueta Denim"),
    marca: "H&M",
  },

  // Ropa - Niños
  {
    nombre: "Polo estampado niño",
    descripcion: "Polo de algodón con estampado divertido, tallas 4 a 12 años.",
    precio: 29.9,
    categoria: "Ropa",
    subcategoria: "Niños",
    stock: 40,
    imagenUrl: img("Polo Nino"),
    marca: "Urbano Kids",
  },
  {
    nombre: "Conjunto deportivo niña",
    descripcion: "Conjunto de buzo y polo deportivo para niña, tallas 4 a 12 años.",
    precio: 69.9,
    categoria: "Ropa",
    subcategoria: "Niños",
    stock: 24,
    imagenUrl: img("Conjunto Nina"),
    marca: "Adidas Kids",
  },
  {
    nombre: "Casaca impermeable niños",
    descripcion: "Casaca liviana e impermeable, ideal para días de lluvia.",
    precio: 74.9,
    categoria: "Ropa",
    subcategoria: "Niños",
    stock: 16,
    imagenUrl: img("Casaca Nino"),
    marca: "Northline Kids",
  },

  // Audífonos
  {
    nombre: "Audífonos inalámbricos Bluetooth",
    descripcion: "Audífonos TWS con estuche de carga, hasta 24 horas de batería total.",
    precio: 149.9,
    categoria: "Audífonos",
    subcategoria: "Inalámbricos",
    stock: 45,
    imagenUrl: img("Audifonos Bluetooth"),
    marca: "JBL",
    destacado: true,
  },
  {
    nombre: "Audífonos in-ear con cable",
    descripcion: "Audífonos con cable y micrófono integrado, conector 3.5mm.",
    precio: 39.9,
    categoria: "Audífonos",
    subcategoria: "Con cable",
    stock: 60,
    imagenUrl: img("Audifonos In Ear"),
    marca: "Sony",
  },
  {
    nombre: "Audífonos gamer con micrófono",
    descripcion: "Audífonos over-ear con micrófono abatible y sonido envolvente 7.1.",
    precio: 179.9,
    categoria: "Audífonos",
    subcategoria: "Gamer",
    stock: 20,
    imagenUrl: img("Audifonos Gamer"),
    marca: "HyperX",
    destacado: true,
  },
  {
    nombre: "Audífonos deportivos resistentes al agua",
    descripcion: "Audífonos inalámbricos con certificación IPX7, ideales para entrenar.",
    precio: 129.9,
    categoria: "Audífonos",
    subcategoria: "Deportivos",
    stock: 30,
    imagenUrl: img("Audifonos Deportivos"),
    marca: "JBL",
  },
  {
    nombre: "Audífonos over-ear cancelación de ruido",
    descripcion: "Audífonos con cancelación activa de ruido y hasta 30 horas de batería.",
    precio: 399.9,
    categoria: "Audífonos",
    subcategoria: "Inalámbricos",
    stock: 12,
    imagenUrl: img("Audifonos Cancelacion Ruido"),
    marca: "Sony",
    destacado: true,
  },
  {
    nombre: "Audífonos TWS mini",
    descripcion: "Audífonos inalámbricos ultra compactos con estuche de carga rápida.",
    precio: 89.9,
    categoria: "Audífonos",
    subcategoria: "Inalámbricos",
    stock: 38,
    imagenUrl: img("Audifonos TWS Mini"),
    marca: "Xiaomi",
  },
  {
    nombre: "Audífonos para correr con gancho",
    descripcion: "Audífonos deportivos con gancho para la oreja, ajuste seguro.",
    precio: 69.9,
    categoria: "Audífonos",
    subcategoria: "Deportivos",
    stock: 27,
    imagenUrl: img("Audifonos Correr"),
    marca: "Xiaomi",
  },
  {
    nombre: "Diadema Bluetooth plegable",
    descripcion: "Diadema inalámbrica plegable, cómoda para uso prolongado.",
    precio: 109.9,
    categoria: "Audífonos",
    subcategoria: "Inalámbricos",
    stock: 19,
    imagenUrl: img("Diadema Bluetooth"),
    marca: "JBL",
  },

  // Calzado
  {
    nombre: "Zapatillas urbanas hombre",
    descripcion: "Zapatillas de cuero sintético, suela flexible, ideales para el día a día.",
    precio: 149.9,
    categoria: "Calzado",
    subcategoria: "Hombre",
    stock: 30,
    imagenUrl: img("Zapatillas Urbanas Hombre"),
    marca: "Nike",
    destacado: true,
  },
  {
    nombre: "Zapatillas running mujer",
    descripcion: "Zapatillas deportivas con amortiguación reactiva, livianas y transpirables.",
    precio: 179.9,
    categoria: "Calzado",
    subcategoria: "Mujer",
    stock: 26,
    imagenUrl: img("Zapatillas Running Mujer"),
    marca: "Adidas",
    destacado: true,
  },
  {
    nombre: "Botines de cuero mujer",
    descripcion: "Botines de cuero con taco bajo, forro interior cómodo.",
    precio: 159.9,
    categoria: "Calzado",
    subcategoria: "Mujer",
    stock: 18,
    imagenUrl: img("Botines Mujer"),
    marca: "Zara",
  },
  {
    nombre: "Zapatos formales hombre",
    descripcion: "Zapatos de cuero para vestir, punta redonda, suela de goma antideslizante.",
    precio: 189.9,
    categoria: "Calzado",
    subcategoria: "Hombre",
    stock: 20,
    imagenUrl: img("Zapatos Formales Hombre"),
    marca: "Aldo",
  },
  {
    nombre: "Sandalias de verano mujer",
    descripcion: "Sandalias planas de tiras, cómodas para uso diario.",
    precio: 49.9,
    categoria: "Calzado",
    subcategoria: "Mujer",
    stock: 34,
    imagenUrl: img("Sandalias Mujer"),
    marca: "H&M",
  },
  {
    nombre: "Zapatillas para niños",
    descripcion: "Zapatillas con velcro, fáciles de poner, suela antideslizante.",
    precio: 89.9,
    categoria: "Calzado",
    subcategoria: "Niños",
    stock: 28,
    imagenUrl: img("Zapatillas Ninos"),
    marca: "Adidas Kids",
  },
  {
    nombre: "Botas de cuero hombre",
    descripcion: "Botas de cuero resistente al agua, ideales para climas fríos.",
    precio: 219.9,
    categoria: "Calzado",
    subcategoria: "Hombre",
    stock: 14,
    imagenUrl: img("Botas Cuero Hombre"),
    marca: "Aldo",
  },
  {
    nombre: "Zapatillas skate unisex",
    descripcion: "Zapatillas de lona reforzada, suela vulcanizada, estilo clásico.",
    precio: 169.9,
    categoria: "Calzado",
    subcategoria: "Unisex",
    stock: 22,
    imagenUrl: img("Zapatillas Skate"),
    marca: "Vans",
  },
  {
    nombre: "Mocasines hombre",
    descripcion: "Mocasines de cuero, corte bajo, ideales para uso casual o de oficina.",
    precio: 139.9,
    categoria: "Calzado",
    subcategoria: "Hombre",
    stock: 19,
    imagenUrl: img("Mocasines Hombre"),
    marca: "Aldo",
  },
  {
    nombre: "Sandalias deportivas hombre",
    descripcion: "Sandalias con velcro ajustable y plantilla acolchada.",
    precio: 99.9,
    categoria: "Calzado",
    subcategoria: "Hombre",
    stock: 25,
    imagenUrl: img("Sandalias Deportivas Hombre"),
    marca: "Nike",
  },

  // Accesorios
  {
    nombre: "Mochila urbana antirrobo",
    descripcion: "Mochila con cierre oculto y compartimento acolchado para laptop.",
    precio: 129.9,
    categoria: "Accesorios",
    subcategoria: "Mochilas",
    stock: 24,
    imagenUrl: img("Mochila Urbana"),
    marca: "Totto",
    destacado: true,
  },
  {
    nombre: "Reloj analógico clásico",
    descripcion: "Reloj de correa de cuero, resistente al agua, diseño minimalista.",
    precio: 159.9,
    categoria: "Accesorios",
    subcategoria: "Relojes",
    stock: 20,
    imagenUrl: img("Reloj Analogico"),
    marca: "Casio",
    destacado: true,
  },
  {
    nombre: "Lentes de sol polarizados",
    descripcion: "Lentes de sol con protección UV400 y cristales polarizados.",
    precio: 99.9,
    categoria: "Accesorios",
    subcategoria: "Lentes",
    stock: 30,
    imagenUrl: img("Lentes de Sol"),
    marca: "Ray-Ban",
  },
  {
    nombre: "Gorra snapback",
    descripcion: "Gorra ajustable de algodón, visera plana.",
    precio: 59.9,
    categoria: "Accesorios",
    subcategoria: "Gorras",
    stock: 40,
    imagenUrl: img("Gorra Snapback"),
    marca: "New Era",
  },
  {
    nombre: "Billetera de cuero hombre",
    descripcion: "Billetera de cuero genuino con múltiples compartimentos para tarjetas.",
    precio: 69.9,
    categoria: "Accesorios",
    subcategoria: "Billeteras",
    stock: 35,
    imagenUrl: img("Billetera Hombre"),
    marca: "Aldo",
  },
  {
    nombre: "Cinturón de cuero reversible",
    descripcion: "Cinturón reversible negro/marrón, hebilla giratoria.",
    precio: 59.9,
    categoria: "Accesorios",
    subcategoria: "Cinturones",
    stock: 32,
    imagenUrl: img("Cinturon Reversible"),
    marca: "Levi's",
  },
  {
    nombre: "Mochila para laptop",
    descripcion: "Mochila acolchada para laptop de hasta 15.6 pulgadas, puerto USB externo.",
    precio: 149.9,
    categoria: "Accesorios",
    subcategoria: "Mochilas",
    stock: 21,
    imagenUrl: img("Mochila Laptop"),
    marca: "Totto",
  },
  {
    nombre: "Reloj deportivo digital",
    descripcion: "Reloj digital resistente al agua, cronómetro y alarma.",
    precio: 89.9,
    categoria: "Accesorios",
    subcategoria: "Relojes",
    stock: 27,
    imagenUrl: img("Reloj Deportivo"),
    marca: "Casio",
  },
  {
    nombre: "Bufanda de lana",
    descripcion: "Bufanda tejida de lana suave, ideal para climas fríos.",
    precio: 39.9,
    categoria: "Accesorios",
    subcategoria: "Bufandas",
    stock: 30,
    imagenUrl: img("Bufanda de Lana"),
    marca: "H&M",
  },
  {
    nombre: "Riñonera urbana",
    descripcion: "Riñonera resistente al agua, ajustable, ideal para salidas cortas.",
    precio: 49.9,
    categoria: "Accesorios",
    subcategoria: "Mochilas",
    stock: 26,
    imagenUrl: img("Rinonera Urbana"),
    marca: "Totto",
  },

  // Hogar (electrodomésticos pequeños)
  {
    nombre: "Licuadora de vaso 600W",
    descripcion: "Licuadora con vaso de vidrio de 1.5L y 3 velocidades.",
    precio: 149.9,
    categoria: "Hogar",
    subcategoria: "Cocina",
    stock: 18,
    imagenUrl: img("Licuadora 600W"),
    marca: "Oster",
    destacado: true,
  },
  {
    nombre: "Sanguichera eléctrica",
    descripcion: "Sanguichera antiadherente con placas para 2 sándwiches.",
    precio: 79.9,
    categoria: "Hogar",
    subcategoria: "Cocina",
    stock: 24,
    imagenUrl: img("Sanguichera Electrica"),
    marca: "Oster",
  },
  {
    nombre: "Plancha a vapor",
    descripcion: "Plancha con suela antiadherente y vapor continuo ajustable.",
    precio: 129.9,
    categoria: "Hogar",
    subcategoria: "Limpieza",
    stock: 20,
    imagenUrl: img("Plancha a Vapor"),
    marca: "Philips",
    destacado: true,
  },
  {
    nombre: "Hervidor eléctrico 1.7L",
    descripcion: "Hervidor de agua inalámbrico con apagado automático.",
    precio: 89.9,
    categoria: "Hogar",
    subcategoria: "Cocina",
    stock: 22,
    imagenUrl: img("Hervidor Electrico"),
    marca: "Oster",
  },
  {
    nombre: "Cafetera de goteo",
    descripcion: "Cafetera con capacidad para 12 tazas y placa de calentamiento.",
    precio: 159.9,
    categoria: "Hogar",
    subcategoria: "Cocina",
    stock: 15,
    imagenUrl: img("Cafetera de Goteo"),
    marca: "Philips",
  },
  {
    nombre: "Aspiradora de mano inalámbrica",
    descripcion: "Aspiradora portátil recargable, ideal para autos y tapicería.",
    precio: 199.9,
    categoria: "Hogar",
    subcategoria: "Limpieza",
    stock: 16,
    imagenUrl: img("Aspiradora Inalambrica"),
    marca: "Black+Decker",
  },
  {
    nombre: "Ventilador de torre",
    descripcion: "Ventilador de torre silencioso con control remoto y 3 velocidades.",
    precio: 179.9,
    categoria: "Hogar",
    subcategoria: "Climatización",
    stock: 12,
    imagenUrl: img("Ventilador de Torre"),
    marca: "Black+Decker",
  },
  {
    nombre: "Tostadora de 2 rebanadas",
    descripcion: "Tostadora con control de dorado ajustable y bandeja recogemigas.",
    precio: 69.9,
    categoria: "Hogar",
    subcategoria: "Cocina",
    stock: 26,
    imagenUrl: img("Tostadora 2 Rebanadas"),
    marca: "Oster",
  },
  {
    nombre: "Batidora de mano",
    descripcion: "Batidora eléctrica de mano con 5 velocidades y accesorios de batido.",
    precio: 79.9,
    categoria: "Hogar",
    subcategoria: "Cocina",
    stock: 23,
    imagenUrl: img("Batidora de Mano"),
    marca: "Philips",
  },
  {
    nombre: "Purificador de aire compacto",
    descripcion: "Purificador con filtro HEPA, ideal para ambientes pequeños.",
    precio: 249.9,
    categoria: "Hogar",
    subcategoria: "Climatización",
    stock: 10,
    imagenUrl: img("Purificador de Aire"),
    marca: "Xiaomi",
  },
];

async function main() {
  console.log(`Sembrando ${productos.length} productos...`);
  await prisma.producto.deleteMany();
  await prisma.producto.createMany({ data: productos });
  console.log("Listo.");
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
